drafting_fonts = ["Tabula Quattro 8", "Comic Neue 8", "ETbb 8", "Special Elite 8"]
export_path = "/var/tabula"

[compose_sequences]
# guillemets
"< <" = "\u00ab"
"> >" = "\u00bb"
# "smart" quotes
"< '" = "\u2018"
"' <" = "\u2018"
"> '" = "\u2019"
"' >" = "\u2019"
"< \"" = "\u201c"
"\" <" = "\u201c"
"> \"" = "\u201d"
"\" >" = "\u201d"
# punctuation
"' '" = "\u02bc"  # modifier letter apostrophe
". ." = "…"
"- - -" = "—"
"- - ." = "–"
"! !" = "\u00a1" # INVERTED EXCLAMATION MARK
"? ?" = "\u00bf" # INVERTED QUESTION MARK
# numerics
"1 4" = "\u00bc" # VULGAR FRACTION ONE QUARTER
"1 2" = "\u00bd" # VULGAR FRACTION ONE HALF
"3 4" = "\u00be" # VULGAR FRACTION THREE QUARTERS
# misc
"o x" = "\u00a4" # CURRENCY SIGN
"x o" = "\u00a4" # CURRENCY SIGN
"o c" = "\u00a9" # COPYRIGHT SIGN
"o C" = "\u00a9" # COPYRIGHT SIGN
"O c" = "\u00a9" # COPYRIGHT SIGN
"O C" = "\u00a9" # COPYRIGHT SIGN
"p !" = "\u00b6" # PILCROW SIGN
"P !" = "\u00b6" # PILCROW SIGN
"P P" = "\u00b6" # PILCROW SIGN
# diacritics and ligature letters
"A E" = "\u00c6" # LATIN CAPITAL LETTER AE
"a e" = "\u00e6" # LATIN SMALL LETTER AE
"O E" = "\u0152" # LATIN CAPITAL LIGATURE OE
"o e" = "\u0153" # LATIN SMALL LIGATURE OE
"` A" = "\u00c0" # LATIN CAPITAL LETTER A WITH GRAVE
"' A" = "\u00c1" # LATIN CAPITAL LETTER A WITH ACUTE
"- A" = "\u0100" # LATIN CAPITAL LETTER A WITH MACRON
"` a" = "\u00e0" # LATIN SMALL LETTER A WITH GRAVE
"' a" = "\u00e1" # LATIN SMALL LETTER A WITH ACUTE
"- a" = "\u0101" # LATIN SMALL LETTER A WITH MACRON
", C" = "\u00c7" # LATIN CAPITAL LETTER C WITH CEDILLA
", c" = "\u00e7" # LATIN SMALL LETTER C WITH CEDILLA
"` E" = "\u00c8" # LATIN CAPITAL LETTER E WITH GRAVE
"' E" = "\u00c9" # LATIN CAPITAL LETTER E WITH ACUTE
"- E" = "\u0112" # LATIN CAPITAL LETTER E WITH MACRON
"` e" = "\u00e8" # LATIN SMALL LETTER E WITH GRAVE
"' e" = "\u00e9" # LATIN SMALL LETTER E WITH ACUTE
"- e" = "\u0113" # LATIN SMALL LETTER E WITH MACRON
"` I" = "\u00cc" # LATIN CAPITAL LETTER I WITH GRAVE
"' I" = "\u00cd" # LATIN CAPITAL LETTER I WITH ACUTE
"- I" = "\u012a" # LATIN CAPITAL LETTER I WITH MACRON
"` i" = "\u00ec" # LATIN SMALL LETTER I WITH GRAVE
"' i" = "\u00ed" # LATIN SMALL LETTER I WITH ACUTE
"- i" = "\u012b" # LATIN SMALL LETTER I WITH MACRON
"~ N" = "\u00d1" # LATIN CAPITAL LETTER N WITH TILDE
"~ n" = "\u00f1" # LATIN SMALL LETTER N WITH TILDE
"` O" = "\u00d2" # LATIN CAPITAL LETTER O WITH GRAVE
"' O" = "\u00d3" # LATIN CAPITAL LETTER O WITH ACUTE
"- O" = "\u014c" # LATIN CAPITAL LETTER O WITH MACRON
"` o" = "\u00f2" # LATIN SMALL LETTER O WITH GRAVE
"' o" = "\u00f3" # LATIN SMALL LETTER O WITH ACUTE
"- o" = "\u014d" # LATIN SMALL LETTER O WITH MACRON
"` U" = "\u00d9" # LATIN CAPITAL LETTER U WITH GRAVE
"' U" = "\u00da" # LATIN CAPITAL LETTER U WITH ACUTE
"- U" = "\u016a" # LATIN CAPITAL LETTER U WITH MACRON
"` u" = "\u00f9" # LATIN SMALL LETTER U WITH GRAVE
"' u" = "\u00fa" # LATIN SMALL LETTER U WITH ACUTE
"- u" = "\u016b" # LATIN SMALL LETTER U WITH MACRON
"\" u" = "\u00fc" # LATIN SMALL LETTER U WITH DIAERESIS
"' Y" = "\u00dd" # LATIN CAPITAL LETTER Y WITH ACUTE
"' y" = "\u00fd" # LATIN SMALL LETTER Y WITH ACUTE
