from AppKit import (
    NSEventModifierFlagCapsLock,
    NSEventModifierFlagShift,
    NSEventModifierFlagControl,
    NSEventModifierFlagOption,
    NSEventModifierFlagCommand,
)

from tabula.device.keyboard_consts import Key

# Values taken from
# /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/
# System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h

KEYCODES = {
    0x00: Key.KEY_A,
    0x01: Key.KEY_S,
    0x02: Key.KEY_D,
    0x03: Key.KEY_F,
    0x04: Key.KEY_H,
    0x05: Key.KEY_G,
    0x06: Key.KEY_Z,
    0x07: Key.KEY_X,
    0x08: Key.KEY_C,
    0x09: Key.KEY_V,
    0x0B: Key.KEY_B,
    0x0C: Key.KEY_Q,
    0x0D: Key.KEY_W,
    0x0E: Key.KEY_E,
    0x0F: Key.KEY_R,
    0x10: Key.KEY_Y,
    0x11: Key.KEY_T,
    0x12: Key.KEY_1,
    0x13: Key.KEY_2,
    0x14: Key.KEY_3,
    0x15: Key.KEY_4,
    0x16: Key.KEY_6,
    0x17: Key.KEY_5,
    0x18: Key.KEY_EQUAL,
    0x19: Key.KEY_9,
    0x1A: Key.KEY_7,
    0x1B: Key.KEY_MINUS,
    0x1C: Key.KEY_8,
    0x1D: Key.KEY_0,
    0x1E: Key.KEY_RIGHTBRACE,
    0x1F: Key.KEY_O,
    0x20: Key.KEY_U,
    0x21: Key.KEY_LEFTBRACE,
    0x22: Key.KEY_I,
    0x23: Key.KEY_P,
    0x25: Key.KEY_L,
    0x26: Key.KEY_J,
    0x27: Key.KEY_APOSTROPHE,
    0x28: Key.KEY_K,
    0x29: Key.KEY_SEMICOLON,
    0x2A: Key.KEY_BACKSLASH,
    0x2B: Key.KEY_COMMA,
    0x2C: Key.KEY_SLASH,
    0x2D: Key.KEY_N,
    0x2E: Key.KEY_M,
    0x2F: Key.KEY_DOT,
    0x32: Key.KEY_GRAVE,
    0x41: Key.KEY_KPDOT,
    0x43: Key.KEY_KPASTERISK,
    0x45: Key.KEY_KPPLUS,
    0x47: Key.KEY_NUMLOCK,
    0x4B: Key.KEY_KPSLASH,
    0x4C: Key.KEY_KPENTER,
    0x4E: Key.KEY_KPMINUS,
    0x51: Key.KEY_KPEQUAL,
    0x52: Key.KEY_KP0,
    0x53: Key.KEY_KP1,
    0x54: Key.KEY_KP2,
    0x55: Key.KEY_KP3,
    0x56: Key.KEY_KP4,
    0x57: Key.KEY_KP5,
    0x58: Key.KEY_KP6,
    0x59: Key.KEY_KP7,
    0x5B: Key.KEY_KP8,
    0x5C: Key.KEY_KP9,
    0x24: Key.KEY_ENTER,
    0x30: Key.KEY_TAB,
    0x31: Key.KEY_SPACE,
    0x33: Key.KEY_BACKSPACE,
    0x35: Key.KEY_ESC,
    0x37: Key.KEY_LEFTMETA,
    0x38: Key.KEY_LEFTSHIFT,
    0x39: Key.KEY_CAPSLOCK,
    0x3A: Key.KEY_LEFTALT,
    0x3B: Key.KEY_LEFTCTRL,
    0x36: Key.KEY_RIGHTMETA,
    0x3C: Key.KEY_RIGHTSHIFT,
    0x3D: Key.KEY_RIGHTALT,
    0x3E: Key.KEY_RIGHTCTRL,
    0x3F: Key.KEY_UNKNOWN,  # Fn key; decide what this should be
    0x40: Key.KEY_F17,
    0x48: Key.KEY_VOLUMEUP,
    0x49: Key.KEY_VOLUMEDOWN,
    0x4A: Key.KEY_MUTE,
    0x4F: Key.KEY_F18,
    0x50: Key.KEY_F19,
    0x5A: Key.KEY_F20,
    0x60: Key.KEY_F5,
    0x61: Key.KEY_F6,
    0x62: Key.KEY_F7,
    0x63: Key.KEY_F3,
    0x64: Key.KEY_F8,
    0x65: Key.KEY_F9,
    0x67: Key.KEY_F11,
    0x69: Key.KEY_F13,
    0x6A: Key.KEY_F16,
    0x6B: Key.KEY_F14,
    0x6D: Key.KEY_F10,
    0x6F: Key.KEY_F12,
    0x71: Key.KEY_F15,
    0x72: Key.KEY_INSERT,
    0x73: Key.KEY_HOME,
    0x74: Key.KEY_PAGEUP,
    0x75: Key.KEY_DELETE,
    0x76: Key.KEY_F4,
    0x77: Key.KEY_END,
    0x78: Key.KEY_F2,
    0x79: Key.KEY_PAGEDOWN,
    0x7A: Key.KEY_F1,
    0x7B: Key.KEY_LEFT,
    0x7C: Key.KEY_RIGHT,
    0x7D: Key.KEY_DOWN,
    0x7E: Key.KEY_UP,
}

MODIFIER_MAP = {
    Key.KEY_LEFTALT: NSEventModifierFlagOption,
    Key.KEY_RIGHTALT: NSEventModifierFlagOption,
    Key.KEY_LEFTSHIFT: NSEventModifierFlagShift,
    Key.KEY_RIGHTSHIFT: NSEventModifierFlagShift,
    Key.KEY_LEFTCTRL: NSEventModifierFlagControl,
    Key.KEY_RIGHTCTRL: NSEventModifierFlagControl,
    Key.KEY_LEFTMETA: NSEventModifierFlagCommand,
    Key.KEY_RIGHTMETA: NSEventModifierFlagCommand,
    Key.KEY_CAPSLOCK: NSEventModifierFlagCapsLock,
}
