from AppKit import (
    NSEventModifierFlagCapsLock,
    NSEventModifierFlagCommand,
    NSEventModifierFlagControl,
    NSEventModifierFlagOption,
    NSEventModifierFlagShift,
)
from tabula.device.eventsource import KeyCode

# Values taken from
# /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.sdk/
# System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/Events.h

KEYCODES = {
    0x00: KeyCode.KEY_A,
    0x01: KeyCode.KEY_S,
    0x02: KeyCode.KEY_D,
    0x03: KeyCode.KEY_F,
    0x04: KeyCode.KEY_H,
    0x05: KeyCode.KEY_G,
    0x06: KeyCode.KEY_Z,
    0x07: KeyCode.KEY_X,
    0x08: KeyCode.KEY_C,
    0x09: KeyCode.KEY_V,
    0x0B: KeyCode.KEY_B,
    0x0C: KeyCode.KEY_Q,
    0x0D: KeyCode.KEY_W,
    0x0E: KeyCode.KEY_E,
    0x0F: KeyCode.KEY_R,
    0x10: KeyCode.KEY_Y,
    0x11: KeyCode.KEY_T,
    0x12: KeyCode.KEY_1,
    0x13: KeyCode.KEY_2,
    0x14: KeyCode.KEY_3,
    0x15: KeyCode.KEY_4,
    0x16: KeyCode.KEY_6,
    0x17: KeyCode.KEY_5,
    0x18: KeyCode.KEY_EQUAL,
    0x19: KeyCode.KEY_9,
    0x1A: KeyCode.KEY_7,
    0x1B: KeyCode.KEY_MINUS,
    0x1C: KeyCode.KEY_8,
    0x1D: KeyCode.KEY_0,
    0x1E: KeyCode.KEY_RIGHTBRACE,
    0x1F: KeyCode.KEY_O,
    0x20: KeyCode.KEY_U,
    0x21: KeyCode.KEY_LEFTBRACE,
    0x22: KeyCode.KEY_I,
    0x23: KeyCode.KEY_P,
    0x25: KeyCode.KEY_L,
    0x26: KeyCode.KEY_J,
    0x27: KeyCode.KEY_APOSTROPHE,
    0x28: KeyCode.KEY_K,
    0x29: KeyCode.KEY_SEMICOLON,
    0x2A: KeyCode.KEY_BACKSLASH,
    0x2B: KeyCode.KEY_COMMA,
    0x2C: KeyCode.KEY_SLASH,
    0x2D: KeyCode.KEY_N,
    0x2E: KeyCode.KEY_M,
    0x2F: KeyCode.KEY_DOT,
    0x32: KeyCode.KEY_GRAVE,
    0x41: KeyCode.KEY_KPDOT,
    0x43: KeyCode.KEY_KPASTERISK,
    0x45: KeyCode.KEY_KPPLUS,
    0x47: KeyCode.KEY_NUMLOCK,
    0x4B: KeyCode.KEY_KPSLASH,
    0x4C: KeyCode.KEY_KPENTER,
    0x4E: KeyCode.KEY_KPMINUS,
    0x51: KeyCode.KEY_KPEQUAL,
    0x52: KeyCode.KEY_KP0,
    0x53: KeyCode.KEY_KP1,
    0x54: KeyCode.KEY_KP2,
    0x55: KeyCode.KEY_KP3,
    0x56: KeyCode.KEY_KP4,
    0x57: KeyCode.KEY_KP5,
    0x58: KeyCode.KEY_KP6,
    0x59: KeyCode.KEY_KP7,
    0x5B: KeyCode.KEY_KP8,
    0x5C: KeyCode.KEY_KP9,
    0x24: KeyCode.KEY_ENTER,
    0x30: KeyCode.KEY_TAB,
    0x31: KeyCode.KEY_SPACE,
    0x33: KeyCode.KEY_BACKSPACE,
    0x35: KeyCode.KEY_ESC,
    0x37: KeyCode.KEY_LEFTMETA,
    0x38: KeyCode.KEY_LEFTSHIFT,
    0x39: KeyCode.KEY_CAPSLOCK,
    0x3A: KeyCode.KEY_LEFTALT,
    0x3B: KeyCode.KEY_LEFTCTRL,
    0x36: KeyCode.KEY_RIGHTMETA,
    0x3C: KeyCode.KEY_RIGHTSHIFT,
    0x3D: KeyCode.KEY_RIGHTALT,
    0x3E: KeyCode.KEY_RIGHTCTRL,
    0x3F: KeyCode.KEY_UNKNOWN,  # Fn key; decide what this should be
    0x40: KeyCode.KEY_F17,
    0x48: KeyCode.KEY_VOLUMEUP,
    0x49: KeyCode.KEY_VOLUMEDOWN,
    0x4A: KeyCode.KEY_MUTE,
    0x4F: KeyCode.KEY_F18,
    0x50: KeyCode.KEY_F19,
    0x5A: KeyCode.KEY_F20,
    0x60: KeyCode.KEY_F5,
    0x61: KeyCode.KEY_F6,
    0x62: KeyCode.KEY_F7,
    0x63: KeyCode.KEY_F3,
    0x64: KeyCode.KEY_F8,
    0x65: KeyCode.KEY_F9,
    0x67: KeyCode.KEY_F11,
    0x69: KeyCode.KEY_F13,
    0x6A: KeyCode.KEY_F16,
    0x6B: KeyCode.KEY_F14,
    0x6D: KeyCode.KEY_F10,
    0x6F: KeyCode.KEY_F12,
    0x71: KeyCode.KEY_F15,
    0x72: KeyCode.KEY_INSERT,
    0x73: KeyCode.KEY_HOME,
    0x74: KeyCode.KEY_PAGEUP,
    0x75: KeyCode.KEY_DELETE,
    0x76: KeyCode.KEY_F4,
    0x77: KeyCode.KEY_END,
    0x78: KeyCode.KEY_F2,
    0x79: KeyCode.KEY_PAGEDOWN,
    0x7A: KeyCode.KEY_F1,
    0x7B: KeyCode.KEY_LEFT,
    0x7C: KeyCode.KEY_RIGHT,
    0x7D: KeyCode.KEY_DOWN,
    0x7E: KeyCode.KEY_UP,
}

MODIFIER_MAP = {
    KeyCode.KEY_LEFTALT: NSEventModifierFlagOption,
    KeyCode.KEY_RIGHTALT: NSEventModifierFlagOption,
    KeyCode.KEY_LEFTSHIFT: NSEventModifierFlagShift,
    KeyCode.KEY_RIGHTSHIFT: NSEventModifierFlagShift,
    KeyCode.KEY_LEFTCTRL: NSEventModifierFlagControl,
    KeyCode.KEY_RIGHTCTRL: NSEventModifierFlagControl,
    KeyCode.KEY_LEFTMETA: NSEventModifierFlagCommand,
    KeyCode.KEY_RIGHTMETA: NSEventModifierFlagCommand,
    KeyCode.KEY_CAPSLOCK: NSEventModifierFlagCapsLock,
}
